travis:
  secure:
    BINSTAR_TOKEN: JjzLMj4KCmeA3JiZY8y73dZNIBoFqXhtJlpktSlrhZXE1vQZLMUBTNYMAexCQl/XUfIr0xreahZX9oMYxbbX0XFOHneVkwZ8COQc9/UEsDBpsOufrpNLcqNemqnBMDCl15VaDAk4t52+3rdZ7aYXaxkeaiMS/mcCQzSvEtT0/aIcbSAPRXVRkfjwbM7uiDfIa2TJ1sYBCg4noWGn4P74QDDmKbjlwLwF5h64PySiBXs7CvRXLdyj6rcbrM6BA928k9akXpN6WO0WyYCn/8Ct0h9MqHKdwMZEp0qwoRdpD2f1heYrdbAMIpkaalzXmz1Zp5QLqLS3Rx6jUJ2VHMkkchfqFT4p7A98SYhjxDGRQfdZ8HeL1ZApI8vVuCl2TIwVCTEKVZ3eK75Wz15CLvtIx8lZX4r20zrMFWNeoxOo8D7geryxS586xf21Mv6q9f2Ckuj+UUMxwFG9NLZD82ckrqdtvUKKDtODDHONyRSuf67FMbsikjLag6az1VS+/lvACaiS6Wda/iguwJ1sOHJivORqKVucFrGk6DsldEQwYkrxyKQUCL0EMNuks8WyjvKDRDN/CYHVBMN8nYosgv3JODn/Ewsx6dxLzhPe1WwfUP7fzCovg4HabfJXFaSXZwyuOHn87Nt+Zu3Ys2PzCuuN0+tYv5tK6OtxAE25bdC2/b0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
